# Generated by Django 2.2 on 2019-12-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photolikes', to='webapp.Image', verbose_name='photo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userlikes', to=settings.AUTH_USER_MODEL, verbose_name='photo')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='userlike',
            field=models.ManyToManyField(blank=True, through='webapp.Like', to=settings.AUTH_USER_MODEL, verbose_name='userslike'),
        ),
    ]
